title: The Underhanded Rust Contest
email: underhanded@rust-lang.org
description: >
  Underhanded Rust is an open, community-wide contest to write innocent-looking
  Rust code that does something underhanded.
baseurl: ""
url: "https://underhanded.rs"
twitter_username: rustlang
github_username:  rust-community

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
google_analytics: UA-88751636-1
